---
# Program/Department Title
title: Center for the Study of Force and Diplomacy
# Subdirectory (with / at only at beginning)
baseurl: /center-for-the-study-of-force-and-diplomacy
# Production domain (without / at the end)
production: https://www.cla.temple.edu
# url spits sitemap
url: https://www.cla.temple.edu/center-for-the-study-of-force-and-diplomacy

# Development Config
# If you do not have access to 'tutheme', use 'minima' instead.
theme: tutheme
palette: light #future feature

# Program Information
# Short tagline for tweets (<100 characters)
tagline: This is our life's work
# Longer descriptions for link previews (<250 characters)
description: 'The Center for the Study of Force and Diplomacy (CENFAD), founded in 1993 by Drs. Richard Immerman, Russell Weigley, and David Rosenberg, fosters interdisciplinary faculty and student research on the historic and contemporary use of force and diplomacy in a global context. CENFAD is housed within Temple University’s History Department.'
# List of related keywords for search engines
keywords: highered, college, university, philadelphia, Temple

# Address
address:
  building: Gladfelter Hall
  room: 918
  street: 1115 Polett Walk
  city: Philadelphia, PA 19122
  email: alan.mcpherson@temple.edu
  phone: 215-204-7466

# University & College Information
university:
  name: Temple University
  url: https://temple.edu/
college:
  name: College of Liberal Arts
  url: https://liberalarts.temple.edu/
  
program_news: https://liberalarts.temple.edu/news/center-for-the-study-of-force-and-diplomacy
program_events: https://events.temple.edu/department/center-for-the-study-of-force-and-diplomacy

# CSV/JSON/YAML data feeds URLs, to be fetched before each build
events-feed: https://liberalarts.temple.edu/events/center-for-the-study-of-force-and-diplomacy/csv
news-feed: https://liberalarts.temple.edu/news/center-for-the-study-of-force-and-diplomacy/csv
articles-feed: https://liberalarts.temple.edu/articles/center-for-the-study-of-force-and-diplomacy/csv
faculty-feed: https://liberalarts.temple.edu/profiles/center-for-the-study-of-force-and-diplomacy/csv
media-mentions-feed: https://liberalarts.temple.edu/media-mentions/center-for-the-study-of-force-and-diplomacy/csv

# Social Media
# Put in only the username unless otherwise noted
# If social media does not apply to your department, keep it blank or use the default values.
# Ff your page does not have a custom URL, create one!
social:
  # Facebook - https://www.facebook.com/CenterfortheStudyofForceandDiplomacy
  facebook: Center for the Study of Force and Diplomacy
  # Twitter - https://twitter.com/USERNAME
  twitter: @CENFAD
  # Instagram - https://www.instagram.com/USERNAME
  instagram: TULiberalArts
  # Snapchat - USERNAME
  snapchat:
  # GitHub - https://github.com/USERNAME or https://github.com/USERNAME/REPO
  github:
  # DeviantArt - http://USERNAME.deviantart.com/
  deviantart:
  # Vimeo - https://vimeo.com/USERNAME
  vimeo:
  # YouTube - Paste the FULL URL below
  youtube:
  # LinkedIn - Paste the FULL URL below
  linkedin:
  # Slack - Paste the FULL URL below
  slack:
  # Google Tag Manager OR Google Analytics
  google_analytics:
  google_tag_manager: GTM-58ZL5B


# Global Site Config
# DO NOT edit below unless if you know what you're doing!
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
timezone: UTC
collections:
  pages:
    title: Pages
    output: true
    layout: page
permalink: /:title

# Prose
prose:
  rooturl: pages
  media: media
  ignore:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
  - index.html
  - _config.yml
  metadata:
    pages:
      - name: title
        field:
          element: text
          label: Title
      - name: permalink
        field:
          element: text
          label: Permalink
      - name: layout
        field:
          element: select
          label: Page layout
          options:
            - name: page
              value: page
            - name: faculty
              value: faculty
            - name: home
              value: home

# Jekyll Ignore
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - s3_website.yml
  - .sass-cache
  - .travis.yml
  - .ruby-version
  - .gitignore
  - vendor
  - _site
  - node_modules
